### ISSUE TITLE
floating point for printf needs enabling

### ISSUE THREAD

**Issue by noutram** [UniversityOfPlymouth-Electronics/Embedded-Systems#1]
```JSON
{
    "target_overrides": {
        "*": {
            "target.printf_lib": "std"
        }
    }
}
`

See   https://github.com/ARMmbed/mbed-os/blob/master/platform/source/minimal-printf/README.md#usage

**Comment by martin2100** [comment]
for bare metal and std printf use in mbed_app.json:-
{
    "requires": ["bare-metal"],

    "target_overrides": {
        "*": {
            "target.printf_lib": "std"
        }
    }
}

**Comment by martin2100** [comment]
{
    "requires": ["bare-metal"],

    "target_overrides": {
        "*": {
            "target.printf_lib": "std"
        }
    }
}

**Comment by noutram** [comment]
If I start with a full mbed-os project, and use the following, that "seems" to cover what we need for years 1 and 2?

{
"requires": ["bare-metal"]
}

**Comment by martin2100** [comment]
Be careful with printf it is reduced by standard so floating point handler doesn't work
________________________________

**Comment by noutram** [comment]
OK, got it :) Many thanks.
