### ISSUE TITLE
back to contents link dosent work

### ISSUE THREAD

**Issue by Benbtl2000** [UniversityOfPlymouth-Electronics/Embedded-Systems#12]
when clicking the back to contents link at the top of the page (https://github.com/UniversityOfPlymouth-Electronics/Embedded-Systems/blob/master/level6/Cplusplus-oop.md) I get a 404 error, belive its a common error, not just that page.

**Comment by noutram** [comment]
Ah yes. Well spotted. Seems the web server uses case sensitive filenames whereas my Windows machine does not.
I think I've fixed them all now. Many thanks!
