### ISSUE TITLE
Overloaded member functions

### ISSUE THREAD

**Issue by Gefry4** [UniversityOfPlymouth-Electronics/Embedded-Systems#13]
The test explanation says "The function setReal is overloaded three times:" 
However, in the co
![temp](https://user-images.githubusercontent.com/36208212/98392839-60e49e00-2050-11eb-8861-cce6afcfe409.png)
de we use setValue instead.

**Comment by noutram** [comment]
It's a typo - it should say "The function setValue is overloaded three times:"

Now fixed
