### ISSUE TITLE
Multiple Inheritance - wrong referred program name (should be Task-340B instead of Task460B)

### ISSUE THREAD

**Issue by benjaminjob** [UniversityOfPlymouth-Electronics/Embedded-Systems#14]
#15 

![image](https://user-images.githubusercontent.com/61531915/98478008-9e7f2d80-21ee-11eb-8799-70b108d414e8.png)

[https://github.com/UniversityOfPlymouth-Electronics/Embedded-Systems/blob/master/level6/Cplusplus-oop.md](url)

> Further topics
Multiple Inheritance
C++ allows us to inherit code from more than one class. You can see an example of this in Task460B

Program given as Task460B which is wrong as this does not exist, should be Task-340B, this program name is correct as ends with -Mult_Inheritance.

**Comment by noutram** [comment]
Many thanks!
