### ISSUE TITLE
TASK 338B #define EXP1 Backwards

### ISSUE THREAD

**Issue by Benbtl2000** [UniversityOfPlymouth-Electronics/Embedded-Systems#16]
In the code of TASK-338B-VirtualFn when you uncomment the #define EXP1 (line 119) it DISABLES the Polymorphism 
but parts 4 and 5 of task 338B suggests the opposite should be true
![image](https://user-images.githubusercontent.com/43821562/98593672-67cb1500-22cb-11eb-82bc-79531c5ba534.png)

**Comment by noutram** [comment]
Well spotted! Now fixed
