### ISSUE TITLE
Multi-Tasking with Interrupts Refers to Task 350 but there are 3 task 350's

### ISSUE THREAD

**Issue by Benbtl2000** [UniversityOfPlymouth-Electronics/Embedded-Systems#19]

**Comment by Benbtl2000** [comment]
![image](https://user-images.githubusercontent.com/43821562/99096537-45d4d980-25ce-11eb-83c2-ee56f1fe564d.png)

The second reference of task 350 with the new CountUp and  CountDown functions don't even seam to exist?

**Comment by noutram** [comment]
Try doing a Git  Fetch Origin. I can only see one task 350
