### ISSUE TITLE
Typo - Dots, Arrows, Value and Reference Semantics (Task310)

### ISSUE THREAD

**Issue by KelsWells** [UniversityOfPlymouth-Electronics/Embedded-Systems#21]
A couple of Typos...

When you assign **once** variable to another using value semantics...

What will happen here is that q will be created separately from p, and each value in p will be copied from **p to p**

**Comment by noutram** [comment]
Thanks. I'll take a look!

**Comment by noutram** [comment]
Many thanks for this - all sorted
