### ISSUE TITLE
Task-350-IntCorrupt\main.cpp: LED labelling (re: interrupts.md)

### ISSUE THREAD

**Issue by rdbanks92** [UniversityOfPlymouth-Electronics/Embedded-Systems#23]
The source code (_main.cpp_) shows shows:
```
DigitalOut red_led(LED3);     //CountUp is in its critical section
DigitalOut yellow_led(LED2);  //CountDown is in its critical section
DigitalOut green_led(LED1);   //counter != 0
```
These are RED, BLUE and GREEN LEDs onboard the NUCLEO F429ZI.

Note, _Interrupt.md_ talks about LEDs RED, YELLOW and GREEN. 

POTENTIAL FIX:
```
DigitalOut red_led(PC_2);     //CountUp is in its critical section
DigitalOut yellow_led(PC_3);  //CountDown is in its critical section
DigitalOut green_led(PC_6);   //counter != 0
```
This would work when utilising the _UOP Module Support Board_ and would save changing the _Interrupt.md_ file whilst maintaining the reference to the RED, YELLOW and GREEN LEDs.

ALTERNATIVE:
```
#include "../lib/uopmsb/uop_msb_2_0_0.h"

DigitalOut red_led(TRAF_RED1_PIN);     //CountUp is in its critical section
DigitalOut yellow_led(TRAF_YEL1_PIN);  //CountDown is in its critical section
DigitalOut green_led(TRAF_GRN1_PIN);   //counter != 0
```

**Comment by noutram** [comment]
Yes, I got my colours confused. Many thanks for spotting this. I've made the changes you suggest. As you point out, it is the smallest changes needed to correct it :)

Many thanks!
