### ISSUE TITLE
Link to ST Link Update Tool is missing from Software List

### ISSUE THREAD

**Issue by motley197** [UniversityOfPlymouth-Electronics/Embedded-Systems#4]
The link here: (Getting Started -> Troubleshooting)

![image](https://user-images.githubusercontent.com/5503433/93360742-e38f7080-f7f8-11ea-9fb3-82e72cf5a7a9.png)

Takes you to the software list but the ST Link Update Tool is missing

**Comment by noutram** [comment]
Well spotted. It had been moved. Link updated.
