### ISSUE TITLE
Broken video links 

### ISSUE THREAD

**Issue by motley197** [UniversityOfPlymouth-Electronics/Embedded-Systems#5]
Embedded-Systems/level4/TASK101.md below the code block there are 3 links to videos, the last one works but the first two are broken - probably the same videos in the previous issues:

![image](https://user-images.githubusercontent.com/5503433/93364113-015ed480-f7fd-11ea-806d-4db5d55900f5.png)

**Comment by noutram** [comment]
Weird bug there. I rejected and reapproved the videos. Now they are visible. Hmmm
