### ISSUE TITLE
Incorrect comment Task 303 

### ISSUE THREAD

**Issue by Benbtl2000** [UniversityOfPlymouth-Electronics/Embedded-Systems#7]
Line 17 of task 303 reads:

        leds = 0xFF;   //Binary 1111111111111111

should be:

        leds = 0xFF;   //Binary 11111111

**Comment by Tom-AW** [comment]
should be

leds = 0xFFFF;      //Binary 1111111111111111

I think it needs the 3rd F at least

**Comment by noutram** [comment]
Now corrected
