### ISSUE TITLE
Lab 1 quiz incorrect answer 

### ISSUE THREAD

**Issue by fordj06** [UniversityOfPlymouth-Electronics/Embedded-Systems#9]
One of the questions in the quiz for lab 1 has an incorrect answer.

**Question:** 

Which of the following is/are true?  

a. When you create an object of type PortOut, all pins on that port are set to output mode automatically.

**Current answer:** False (feedback Comment: Incorrrect. You provide a mask to specify which pins are set as an output.)

According to the [MBED documentaion](https://os.mbed.com/docs/mbed-os/v6.3/apis/portout.html): 

The default mask value is 0xFFFFFFFF which sets all pins as an output.

**Comment by noutram** [comment]
Fixed - with thanks :)
